# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: NuGetCommand@2
  displayName: package the assembly
  inputs:
    command: pack
    packagesToPack: '!**/*.[Tt]est.csproj'
    versioningScheme: byBuildNumber

- task: NuGetCommand@2
    displayName: publish package
    inputs:
        command: push
        publishToVstsFeed: 'RelationalMapper'
        allowPackageconflicts: true
