on:
  push:
    branches:
      - trunk 


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '3.1.x', '5.0.x' ]   
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: sed 's/TOKEN/%GITHUB_TOKEN%/'  ./nuget.config

    - name: build and test and publish
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        dotnet restore
        dotnet build --configuration Release --no-restore
        dotnet test --no-restore --verbosity normal /p:CollectCoverage=true  /p:CoverletOutputFormat=cobertura  
        VERSION_TAG=$(git describe --tags)
        dotnet pack -p:PackageId=NOSQLORM -p:PackageVersion=$VERSION_TAG --configuration Release --no-restore -o "../../packages"

        dotnet nuget push ../packages/*.nupkg  --source "github" -k $GITHUB_TOKEN


