on:
  push:
    branches:
      - trunk 


jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0




    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - run: sed 's/TOKEN/%GITHUB_TOKEN%/'  ./nuget.config
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: build and test and publish
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        dotnet restore
        dotnet build --configuration Release --no-restore
        dotnet test --no-restore --verbosity normal -o "./TestResults" /p:CollectCoverage=true  /p:CoverletOutputFormat=cobertura /p:CoverletOutput="./TestResults/Coverage"
        VERSION_TAG=$(git describe --tags)
        dotnet pack -p:PackageId=NOSQLORM -p:PackageVersion=$VERSION_TAG --configuration Release --no-restore -o "../../packages"

        dotnet nuget push ../../packages/*.nupkg  --source "github" -k $GITHUB_TOKEN


    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=hucklebe
          -Dsonar.projectKey=${{ secrets.SONAR_PRJ_KEY }}
          -Dsonar.verbose=true
          -Dsonar.cs.xunit.reportPaths=./TestResults
