name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.806

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal /p:CollectCoverage=true  /p:CoverletOutputFormat=cobertura   
    - name: get_version

      run: |
        echo ::set-env name=VERSION_TAG::$(git describe --tags)


    - name: package
      run: dotnet pack -p:PackageVersion=$VERSION_TAG --configuration Release --no-restore

    - name: publish
      run: |
        filepath="bin/Release/com.brgs.orm.$VERSION_TAG.nupkg"
        dotnet nuget push $filepath --source "https://nuget.pkg.github.com/badgerowluke/index.json" -k ${{ secrets.GITHUB_TOKEN }}

